### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by RUSshy** [zyedidia/sfml#1]
Hello

I'm importing your lib using : 

import (
	"github.com/zyedidia/sfml/v2.3/sfml"
	"runtime"
)

But then i get load of error, where do i put include folder? i don't understand, can you help me please?

Thanks

**Comment by zyedidia** [comment]
This is just a Github mirror of a Gitlab project you can find [here](https://gitlab.com/tapir/sfml). I'm not the maker of the project.

I can probably still help you install it though. Are you using Windows or Mac or Linux?

**Comment by RUSshy** [comment]
I'm on osx, i tried with the origial repo but i have same issue:


../../../go/src/gitlab.com/tapir/sfml/v2.3/sfml/vertexArray.go:81: cannot use v.data (type *C.struct_sfVertexArray) as type *C.struct_sfSprite in argument to func literal
../../../go/src/gitlab.com/tapir/sfml/v2.3/sfml/vertexArray.go:83: cannot use v.data (type *C.struct_sfVertexArray) as type *C.struct_sfSprite in argument to func literal
../../../go/src/gitlab.com/tapir/sfml/v2.3/sfml/vertexArray.go:91: cannot use v.data (type *C.struct_sfVertexArray) as type *C.struct_sfSprite in argument to func literal
../../../go/src/gitlab.com/tapir/sfml/v2.3/sfml/vertexArray.go:93: cannot use v.data (type *C.struct_sfVertexArray) as type *C.struct_sfSprite in argument to func literal

**Comment by RUSshy** [comment]
I installed SFLM and CSFML using homebrew (sfml-2.4.2 and csfml-2.3_1)

**Comment by zyedidia** [comment]
Oh right now I remember why I didn't use this -- it has errors. I recommend that instead you use another binding of sfml for Go which you can find here: https://github.com/manyminds/gosfml.

Then you can use it like:

```go
package main

import sf "github.com/manyminds/gosfml"
import "runtime"

const (
	screenWidth  = 800
	screenHeight = 600
)

func init() {
    runtime.LockOSThread()
}

func main() {
	window := sf.NewRenderWindow(sf.VideoMode{screenWidth, screenHeight, 32}, "Rectangle", sf.StyleDefault, sf.DefaultContextSettings())
	window.SetVSyncEnabled(true)
	window.SetFramerateLimit(60)

	rect, _ := sf.NewRectangleShape()
	rect.SetSize(sf.Vector2f{30, 30})
	rect.SetFillColor(sf.ColorBlue())
	rect.SetOrigin(sf.Vector2f{15, 15})
	rect.SetPosition(sf.Vector2f{screenWidth / 2, screenHeight / 2})

	for window.IsOpen() {
		for event := window.PollEvent(); event != nil; event = window.PollEvent() {
			switch ev := event.(type) {
			case sf.EventKeyReleased:
				if ev.Code == sf.KeyEscape {
					window.Close()
				}
			case sf.EventClosed:
				window.Close()
			}
		}

		window.Clear(sf.ColorWhite())
		window.Draw(rect, sf.DefaultRenderStates())
		window.Display()
	}
}
```

**Comment by zyedidia** [comment]
Maybe in the future I'll try to fix the bugs in this repository, but like I said, I'm not the one who wrote it.

**Comment by RUSshy** [comment]
Oh this one works fine :), but it takes a long time to rum ~ 10+ seconds, is that normal ? 0o

**Comment by zyedidia** [comment]
Yeah it takes a long time to compile it because it uses cgo. I think if you use `go install` to build it will cache the build so in the future it won't take as long. It might even do that with `go run` or `go build` but I'm not sure.

**Comment by RUSshy** [comment]
It is so much faster now, not instant but faster, thanks a lot you saved me ton of hours of googling xD

**Comment by zyedidia** [comment]
Glad I could help :).

**Comment by zyedidia** [comment]
I fixed those errors so you can use this repository now if you'd like. The nice thing about this wrapper is that it doesn't return unnecessary error variables and also has nicer functions.

**Comment by RUSshy** [comment]
I'll try it, thanks again :)
